language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: 1.31.0

    - rust: nightly
      script:
        - cargo test
        - cargo test --features nightly


script:
  - cargo test
